# -*- coding: utf-8 -*-
"""PyQt UI base class for the main TurkeyGeoMorph dialog."""

from PyQt5 import QtCore, QtGui, QtWidgets
from qgis.gui import QgsFileWidget, QgsMapCanvas


class Ui_TurkeyGeoMorphDialog(object):
    """Programmatic equivalent of the Qt Designer main dialog."""

    def setupUi(self, TurkeyGeoMorphDialog):
        """Create all widgets."""
        TurkeyGeoMorphDialog.setObjectName("TurkeyGeoMorphDialog")
        TurkeyGeoMorphDialog.resize(980, 680)
        TurkeyGeoMorphDialog.setMinimumSize(720, 520)
        TurkeyGeoMorphDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(TurkeyGeoMorphDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(TurkeyGeoMorphDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setUsesScrollButtons(True)
        self.verticalLayout.addWidget(self.tabWidget)

        self._setup_workspace_tab()
        self._setup_download_tab()
        self._setup_maps_tab()
        self._setup_export_tab()
        self._setup_report_tab()
        self._setup_run_tab()
        self.retranslateUi(TurkeyGeoMorphDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TurkeyGeoMorphDialog)

    def _setup_workspace_tab(self):
        self.tabWorkspace = QtWidgets.QWidget()
        self.tabWorkspace.setObjectName("tabWorkspace")
        layout = QtWidgets.QGridLayout(self.tabWorkspace)
        self.labelWorkspaceHelp = QtWidgets.QLabel(self.tabWorkspace)
        self.labelWorkspaceHelp.setWordWrap(True)
        self.labelWorkspaceHelp.setStyleSheet("color:#34495e;background:#f4f7fb;border:1px solid #d8e1ef;padding:8px;")
        self.cmbProvince = QtWidgets.QComboBox(self.tabWorkspace)
        self.cmbProvince.setObjectName("cmbProvince")
        self.cmbDistrict = QtWidgets.QComboBox(self.tabWorkspace)
        self.cmbDistrict.setObjectName("cmbDistrict")
        self.radioProvinceBoundary = QtWidgets.QRadioButton(self.tabWorkspace)
        self.radioProvinceBoundary.setObjectName("radioProvinceBoundary")
        self.radioProvinceBoundary.setChecked(True)
        self.radioDistrictBoundary = QtWidgets.QRadioButton(self.tabWorkspace)
        self.radioDistrictBoundary.setObjectName("radioDistrictBoundary")
        self.radioManualBoundary = QtWidgets.QRadioButton(self.tabWorkspace)
        self.radioManualBoundary.setObjectName("radioManualBoundary")
        self.mapCanvas = QgsMapCanvas(self.tabWorkspace)
        self.mapCanvas.setObjectName("mapCanvas")
        self.btnShowBoundary = QtWidgets.QPushButton(self.tabWorkspace)
        self.btnShowBoundary.setObjectName("btnShowBoundary")
        self.lineOutputFolder = QtWidgets.QLineEdit(self.tabWorkspace)
        self.lineOutputFolder.setObjectName("lineOutputFolder")
        self.btnBrowseOutput = QtWidgets.QPushButton(self.tabWorkspace)
        self.btnBrowseOutput.setObjectName("btnBrowseOutput")
        self.lineProjectName = QtWidgets.QLineEdit(self.tabWorkspace)
        self.lineProjectName.setObjectName("lineProjectName")
        self.lineProjectName.setText("jeomorfoloji_analizi")
        self.labelOutputHelp = QtWidgets.QLabel(self.tabWorkspace)
        self.labelOutputHelp.setWordWrap(True)
        self.labelOutputHelp.setStyleSheet("color:#555;")
        self.labelProjectNameHelp = QtWidgets.QLabel(self.tabWorkspace)
        self.labelProjectNameHelp.setWordWrap(True)
        self.labelProjectNameHelp.setStyleSheet("color:#555;")

        self.groupBoundary = QtWidgets.QGroupBox(self.tabWorkspace)
        self.groupBoundary.setObjectName("groupBoundary")
        boundary_layout = QtWidgets.QHBoxLayout(self.groupBoundary)
        boundary_layout.addWidget(self.radioProvinceBoundary)
        boundary_layout.addWidget(self.radioDistrictBoundary)
        boundary_layout.addWidget(self.radioManualBoundary)
        layout.addWidget(self.labelWorkspaceHelp, 0, 0, 1, 4)
        layout.addWidget(QtWidgets.QLabel("İl"), 1, 0)
        layout.addWidget(self.cmbProvince, 1, 1)
        layout.addWidget(QtWidgets.QLabel("İlçe"), 2, 0)
        layout.addWidget(self.cmbDistrict, 2, 1)
        layout.addWidget(self.groupBoundary, 3, 0, 1, 2)
        layout.addWidget(self.btnShowBoundary, 4, 0, 1, 2)
        layout.addWidget(QtWidgets.QLabel("Çıktı klasörü"), 5, 0)
        layout.addWidget(self.lineOutputFolder, 5, 1)
        layout.addWidget(self.btnBrowseOutput, 5, 2)
        layout.addWidget(self.labelOutputHelp, 6, 1, 1, 2)
        layout.addWidget(QtWidgets.QLabel("Proje adı"), 7, 0)
        layout.addWidget(self.lineProjectName, 7, 1, 1, 2)
        layout.addWidget(self.labelProjectNameHelp, 8, 1, 1, 2)
        layout.addWidget(self.mapCanvas, 1, 3, 8, 1)
        layout.setColumnStretch(3, 1)
        self.tabWidget.addTab(self.tabWorkspace, "")

    def _setup_download_tab(self):
        self.tabDownload = QtWidgets.QWidget()
        self.tabDownload.setObjectName("tabDownload")
        layout = QtWidgets.QVBoxLayout(self.tabDownload)
        self.groupWorkflow = QtWidgets.QGroupBox(self.tabDownload)
        self.groupWorkflow.setObjectName("groupWorkflow")
        workflow_layout = QtWidgets.QVBoxLayout(self.groupWorkflow)
        self.labelWorkflow = QtWidgets.QLabel(self.groupWorkflow)
        self.labelWorkflow.setWordWrap(True)
        workflow_layout.addWidget(self.labelWorkflow)
        layout.addWidget(self.groupWorkflow)

        self.groupDemSource = QtWidgets.QGroupBox(self.tabDownload)
        source_layout = QtWidgets.QGridLayout(self.groupDemSource)
        self.demSourceButtons = QtWidgets.QButtonGroup(self.groupDemSource)
        sources = [
            ("radioCopernicus", "Copernicus DEM GLO-30 — 30m | ESA/AWS | kimliksiz"),
            ("radioOpenTopo30", "OpenTopography — 30m | COP30 | API key gerekli"),
            ("radioOpenTopo90", "OpenTopography — 90m | SRTMGL3 | API key gerekli"),
            ("radioTandemx", "TanDEM-X 90m | DLR | manuel indirilen dosya"),
            ("radioLocalDem", "Yerel DEM Dosyası — kendi verinizi kullanın"),
        ]
        for row, item in enumerate(sources):
            radio = QtWidgets.QRadioButton(self.groupDemSource)
            radio.setObjectName(item[0])
            radio.setText(item[1])
            if row == 1:  # OpenTopography 30m varsayılan olarak seçili
                radio.setChecked(True)
            setattr(self, item[0], radio)
            self.demSourceButtons.addButton(radio)
            source_layout.addWidget(radio, row // 2, row % 2)
        layout.addWidget(self.groupDemSource)

        self.groupCredentials = QtWidgets.QGroupBox(self.tabDownload)
        cred_layout = QtWidgets.QGridLayout(self.groupCredentials)
        self.lineOpenTopoKey = QtWidgets.QLineEdit(self.groupCredentials)
        self.btnValidateOpenTopo = QtWidgets.QPushButton(self.groupCredentials)
        self.labelCredentialInfo = QtWidgets.QLabel(self.groupCredentials)
        self.labelCredentialInfo.setOpenExternalLinks(True)
        self.fileTandemx = QgsFileWidget(self.groupCredentials)
        self.fileTandemx.setFilter("Raster (*.tif *.tiff *.img *.vrt)")
        self.fileLocalDem = QgsFileWidget(self.groupCredentials)
        self.fileLocalDem.setFilter("Raster (*.tif *.tiff *.hgt *.img *.asc *.vrt *.nc *.h5 *.hdf5)")
        self.labelLocalDemInfo = QtWidgets.QLabel(self.groupCredentials)
        fields = [
            ("OpenTopography API key", self.lineOpenTopoKey),
            ("TanDEM-X dosyası", self.fileTandemx),
            ("Yerel DEM dosyası", self.fileLocalDem),
        ]
        for row, item in enumerate(fields):
            cred_layout.addWidget(QtWidgets.QLabel(item[0]), row, 0)
            cred_layout.addWidget(item[1], row, 1)
        cred_layout.addWidget(self.btnValidateOpenTopo, 0, 2)
        cred_layout.addWidget(self.labelCredentialInfo, 3, 0, 1, 3)
        cred_layout.addWidget(self.labelLocalDemInfo, 4, 0, 1, 3)
        layout.addWidget(self.groupCredentials)

        self.groupOsm = QtWidgets.QGroupBox(self.tabDownload)
        osm_layout = QtWidgets.QGridLayout(self.groupOsm)
        self.checkDownloadRivers = QtWidgets.QCheckBox(self.groupOsm)
        self.checkDownloadRivers.setChecked(True)
        self.cmbRiverFilter = QtWidgets.QComboBox(self.groupOsm)
        self.cmbRiverFilter.addItems([
            "Tümü", "river+stream", "Yalnızca river",
            "Kanal ve drenaj dahil", "Mevsimlik dahil"
        ])
        self.checkClipRivers = QtWidgets.QCheckBox(self.groupOsm)
        self.checkClipRivers.setChecked(True)
        osm_layout.addWidget(self.checkDownloadRivers, 0, 0)
        osm_layout.addWidget(QtWidgets.QLabel("Kaynak: download.geofabrik.de/europe/turkey-latest.osm.pbf"), 1, 0, 1, 2)
        osm_layout.addWidget(QtWidgets.QLabel("Not: ~80MB PBF dosyası, yalnızca waterway tag'leri işlenir"), 2, 0, 1, 2)
        osm_layout.addWidget(QtWidgets.QLabel("Filtre"), 3, 0)
        osm_layout.addWidget(self.cmbRiverFilter, 3, 1)
        osm_layout.addWidget(self.checkClipRivers, 4, 0, 1, 2)
        layout.addWidget(self.groupOsm)

        self.tabWidget.addTab(self.tabDownload, "")

    def _map_tab(self, name):
        tab = QtWidgets.QWidget()
        layout = QtWidgets.QFormLayout(tab)
        check = QtWidgets.QCheckBox(tab)
        check.setText("Bu haritayı üret")
        check.setChecked(False)
        layout.addRow(check)
        line = QtWidgets.QFrame(tab)
        line.setFrameShape(QtWidgets.QFrame.HLine)
        layout.addRow(line)
        return tab, layout, check

    def _setup_maps_tab(self):
        self.tabMaps = QtWidgets.QWidget()
        outer = QtWidgets.QVBoxLayout(self.tabMaps)
        self.mapsTabs = QtWidgets.QTabWidget(self.tabMaps)
        outer.addWidget(self.mapsTabs)

        tab, layout, self.checkElevationMap = self._map_tab("Yükselti")
        self.cmbElevationPalette = QtWidgets.QComboBox(tab)
        self.cmbElevationPalette.addItems(["Klasik Terrain", "Viridis", "Magma", "Plasma", "Inferno", "DEM Screen", "Mavi-Yeşil-Sarı-Kırmızı", "Özel Türkiye Paleti"])
        self.spinElevationClasses = QtWidgets.QSpinBox(tab)
        self.spinElevationClasses.setRange(5, 20)
        self.spinElevationClasses.setValue(10)
        self.sliderElevationOpacity = QtWidgets.QSlider(QtCore.Qt.Horizontal, tab)
        self.sliderElevationOpacity.setRange(0, 100)
        self.checkElevationHillshade = QtWidgets.QCheckBox(tab)
        self.checkElevationContours = QtWidgets.QCheckBox(tab)
        self.spinContourInterval = QtWidgets.QDoubleSpinBox(tab)
        self.spinContourInterval.setValue(100)
        self.cmbContourStyle = QtWidgets.QComboBox(tab)
        self.cmbContourStyle.addItems(["Ana/ara eğri", "Yalnızca ana eğri"])
        for label, widget in [("Renk paleti", self.cmbElevationPalette), ("Sınıf sayısı", self.spinElevationClasses), ("Şeffaflık", self.sliderElevationOpacity), ("Hillshade altlık", self.checkElevationHillshade), ("Eşyükselti eğrileri", self.checkElevationContours), ("Eğri aralığı", self.spinContourInterval), ("Eğri stili", self.cmbContourStyle)]:
            layout.addRow(label, widget)
        self.mapsTabs.addTab(tab, "Yükselti")

        tab, layout, self.checkHillshadeMap = self._map_tab("Hillshade")
        self.dialHillshadeAzimuth = QtWidgets.QDial(tab)
        self.dialHillshadeAzimuth.setRange(0, 360)
        self.dialHillshadeAzimuth.setValue(315)
        self.spinHillshadeAzimuth = QtWidgets.QSpinBox(tab)
        self.spinHillshadeAzimuth.setRange(0, 360)
        self.spinHillshadeAzimuth.setValue(315)
        self.spinHillshadeAltitude = QtWidgets.QSpinBox(tab)
        self.spinHillshadeAltitude.setRange(0, 90)
        self.spinHillshadeAltitude.setValue(45)
        self.spinHillshadeZ = QtWidgets.QDoubleSpinBox(tab)
        self.spinHillshadeZ.setRange(1.0, 5.0)
        self.spinHillshadeZ.setValue(1.0)
        self.checkMultidirectionalHillshade = QtWidgets.QCheckBox(tab)
        self.cmbHillshadeColorMode = QtWidgets.QComboBox(tab)
        self.cmbHillshadeColorMode.addItems(["Gri", "Renkli", "Sepia"])
        for label, widget in [("Azimut dial", self.dialHillshadeAzimuth), ("Azimut", self.spinHillshadeAzimuth), ("Yükseklik açısı", self.spinHillshadeAltitude), ("Z faktörü", self.spinHillshadeZ), ("Çok yönlü", self.checkMultidirectionalHillshade), ("Renk modu", self.cmbHillshadeColorMode)]:
            layout.addRow(label, widget)
        self.mapsTabs.addTab(tab, "Hillshade")

        tab, layout, self.checkSlopeMap = self._map_tab("Eğim")
        self.radioSlopeDegree = QtWidgets.QRadioButton("Derece°", tab)
        self.radioSlopeDegree.setChecked(True)
        self.radioSlopePercent = QtWidgets.QRadioButton("Yüzde%", tab)
        unit_box = QtWidgets.QWidget(tab)
        unit_layout = QtWidgets.QHBoxLayout(unit_box)
        unit_layout.addWidget(self.radioSlopeDegree)
        unit_layout.addWidget(self.radioSlopePercent)
        self.cmbSlopeAlgorithm = QtWidgets.QComboBox(tab)
        self.cmbSlopeAlgorithm.addItems(["Horn", "ZevenbergenThorne"])
        self.cmbSlopeClass = QtWidgets.QComboBox(tab)
        self.cmbSlopeClass.addItems(["FAO standartı", "Corine Arazi Örtüsü", "Türkiye Toprak Sınıflaması", "Manuel", "Sürekli"])
        self.tableSlopeClasses = QtWidgets.QTableWidget(7, 3, tab)
        self.tableSlopeClasses.setHorizontalHeaderLabels(["Sınıf", "Alt sınır", "Renk"])
        self.tableSlopeClasses.setMaximumHeight(150)
        for label, widget in [("Birim", unit_box), ("Algoritma", self.cmbSlopeAlgorithm), ("Sınıflandırma", self.cmbSlopeClass), ("Özel sınırlar", self.tableSlopeClasses)]:
            layout.addRow(label, widget)
        self.mapsTabs.addTab(tab, "Eğim")

        tab, layout, self.checkAspectMap = self._map_tab("Bakı")
        self.cmbAspectDirections = QtWidgets.QComboBox(tab)
        self.cmbAspectDirections.addItems(["4 yön", "8 yön", "16 yön"])
        self.cmbAspectDirections.setCurrentIndex(1)
        self.checkAspectFlat = QtWidgets.QCheckBox(tab)
        self.cmbAspectScheme = QtWidgets.QComboBox(tab)
        self.cmbAspectScheme.addItems(["Kompas", "Sıcak-Soğuk", "Özel"])
        layout.addRow("Yön sayısı", self.cmbAspectDirections)
        layout.addRow("Düz alanlar", self.checkAspectFlat)
        layout.addRow("Renk şeması", self.cmbAspectScheme)
        self.mapsTabs.addTab(tab, "Bakı")

        for attr, title, fields in [
            ("Curvature", "Eğrisellik", [("Tür", ["Profil eğriliği", "Plan eğriliği", "Toplam eğrisellik", "Teğetsel eğrisellik", "Uzunlamasına eğrisellik"]), ("Ölçek faktörü", "double"), ("Sınıflandırma", ["3 sınıf", "5 sınıf", "Sürekli"])]),
            ("Twi", "TWI", [("Akış algoritması", ["D8", "D-Infinity", "MFD"]), ("Minimum katkı alanı", "spin"), ("Çukur doldurma", "check")]),
            ("Rivers", "Akarsu Ağı", [("Veri kaynağı", ["OSM Geofabrik verisi kullan", "DEM'den türet", "İkisini birleştir"]), ("DEM eşik değeri", "spinbig"), ("Strahler göster", "check"), ("Minimum sıra", "smallspin"), ("Havza sınırları", "check"), ("Tampon bölge", "check"), ("Tampon mesafesi", "double")]),
            ("Geomorphons", "Morfolojik Birimler", [("Pencere boyutu", "oddspin"), ("Eşik açısı", "double"), ("Sınıf sayısı", ["10 standart", "6 basitleştirilmiş"])]),
            ("Tpi", "TPI", [("İç yarıçap", "spin"), ("Dış yarıçap", "spin"), ("Sınıflandırma", ["Weiss 6 sınıf", "Özel"])]),
            ("Relief", "Rölyef Enerjisi", [("Pencere boyutu", "oddspin"), ("Hesaplama", ["Maks-Min", "Standart Sapma", "Ortalama"]), ("Sınıf aralıkları", "table")]),
        ]:
            tab, layout, check = self._map_tab(title)
            setattr(self, "check{0}Map".format(attr), check)
            for label, spec in fields:
                widget = self._create_option_widget(tab, spec)
                setattr(self, "widget{0}{1}".format(attr, label.replace(" ", "")), widget)
                layout.addRow(label, widget)
            self.mapsTabs.addTab(tab, title)

        self.tabWidget.addTab(self.tabMaps, "")

    def _create_option_widget(self, parent, spec):
        if isinstance(spec, list):
            combo = QtWidgets.QComboBox(parent)
            combo.addItems(spec)
            return combo
        if spec == "check":
            return QtWidgets.QCheckBox(parent)
        if spec == "double":
            spin = QtWidgets.QDoubleSpinBox(parent)
            spin.setRange(0, 111120)
            spin.setValue(1)
            return spin
        if spec == "spinbig":
            spin = QtWidgets.QSpinBox(parent)
            spin.setRange(100, 50000)
            spin.setValue(1000)
            return spin
        if spec == "smallspin":
            spin = QtWidgets.QSpinBox(parent)
            spin.setRange(1, 8)
            return spin
        if spec == "oddspin":
            spin = QtWidgets.QSpinBox(parent)
            spin.setRange(3, 51)
            spin.setSingleStep(2)
            spin.setValue(9)
            return spin
        if spec == "table":
            table = QtWidgets.QTableWidget(5, 3, parent)
            table.setHorizontalHeaderLabels(["Sınıf", "Alt", "Üst"])
            table.setMaximumHeight(130)
            return table
        spin = QtWidgets.QSpinBox(parent)
        spin.setRange(1, 10000)
        spin.setValue(100)
        return spin

    def _setup_export_tab(self):
        self.tabExport = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout(self.tabExport)
        self.labelExportIntro = QtWidgets.QLabel(self.tabExport)
        self.labelExportIntro.setWordWrap(True)
        self.checkPdf = QtWidgets.QCheckBox("PDF", self.tabExport)
        self.checkPng = QtWidgets.QCheckBox("PNG", self.tabExport)
        self.checkGeotiff = QtWidgets.QCheckBox("GeoTIFF", self.tabExport)
        self.checkSvg = QtWidgets.QCheckBox("SVG", self.tabExport)
        self.checkQgisProject = QtWidgets.QCheckBox("QGIS Projesi", self.tabExport)
        self.checkExportVectors = QtWidgets.QCheckBox("Vektör verileri", self.tabExport)
        self.checkCreateArchive = QtWidgets.QCheckBox("Teslim paketini ZIP olarak oluştur", self.tabExport)
        self.checkCreateManifest = QtWidgets.QCheckBox("Dosya manifesti ve özet log oluştur", self.tabExport)
        self.checkPdf.setChecked(True)
        self.checkPng.setChecked(False)
        self.checkGeotiff.setChecked(False)
        self.checkSvg.setChecked(False)
        self.checkQgisProject.setChecked(True)
        self.checkExportVectors.setChecked(False)
        self.checkCreateArchive.setChecked(False)
        self.checkCreateManifest.setChecked(False)
        self.cmbPngDpi = QtWidgets.QComboBox(self.tabExport)
        self.cmbPngDpi.addItems(["150", "300", "600"])
        self.cmbPngDpi.setCurrentText("150")
        self.lineExportPrefix = QtWidgets.QLineEdit(self.tabExport)
        self.lineExportPrefix.setPlaceholderText("Dosya adı ön eki")
        self.labelFormatHelp = QtWidgets.QLabel(self.tabExport)
        self.labelFormatHelp.setWordWrap(True)
        self.labelFormatHelp.setStyleSheet("color:#555;background:#fbfbfb;border:1px solid #ddd;padding:6px;")
        fmt_box = QtWidgets.QGroupBox("Formatlar", self.tabExport)
        fmt_layout = QtWidgets.QGridLayout(fmt_box)
        fmt_layout.addWidget(self.checkPdf, 0, 0)
        fmt_layout.addWidget(self.checkPng, 0, 1)
        fmt_layout.addWidget(QtWidgets.QLabel("PNG DPI:", self.tabExport), 0, 2)
        fmt_layout.addWidget(self.cmbPngDpi, 0, 3)
        fmt_layout.addWidget(self.checkSvg, 0, 4)
        fmt_layout.addWidget(self.checkGeotiff, 1, 0)
        fmt_layout.addWidget(self.checkExportVectors, 1, 1)
        fmt_layout.addWidget(self.checkQgisProject, 1, 2)
        fmt_layout.addWidget(self.checkCreateManifest, 1, 3)
        fmt_layout.addWidget(self.checkCreateArchive, 1, 4)
        fmt_layout.addWidget(QtWidgets.QLabel("Ön ek:", self.tabExport), 2, 0)
        fmt_layout.addWidget(self.lineExportPrefix, 2, 1, 1, 4)
        fmt_layout.addWidget(self.labelFormatHelp, 3, 0, 1, 5)
        self.treeExportFiles = QtWidgets.QTreeWidget(self.tabExport)
        self.treeExportFiles.setHeaderLabels(["Öğe", "Tür", "Durum"])
        self.treeExportFiles.setAlternatingRowColors(True)
        self.treeExportFiles.setRootIsDecorated(True)
        self.labelExportProgress = QtWidgets.QLabel(
            "Dışa aktarma ilerlemesi:", self.tabExport)
        self.exportProgress = QtWidgets.QProgressBar(self.tabExport)
        self.exportProgress.setValue(0)
        self.btnGenerateAllMaps = QtWidgets.QPushButton(self.tabExport)
        self.btnGenerateAllMaps.setMinimumHeight(34)
        self.btnGenerateAllMaps.setStyleSheet("background:#1e5aa8;color:white;font-weight:bold;")
        self.textExportInfo = QtWidgets.QTextEdit(self.tabExport)
        self.textExportInfo.setReadOnly(True)
        splitter = QtWidgets.QSplitter(QtCore.Qt.Vertical, self.tabExport)
        splitter.addWidget(self.treeExportFiles)
        splitter.addWidget(self.textExportInfo)
        splitter.setStretchFactor(0, 3)
        splitter.setStretchFactor(1, 1)
        layout.addWidget(self.labelExportIntro)
        layout.addWidget(fmt_box)
        layout.addWidget(splitter)
        layout.addWidget(self.labelExportProgress)
        layout.addWidget(self.exportProgress)
        layout.addWidget(self.btnGenerateAllMaps)
        self.tabWidget.addTab(self.tabExport, "")

    def _setup_report_tab(self):
        self.tabReport = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout(self.tabReport)
        self.labelReportIntro = QtWidgets.QLabel(self.tabReport)
        self.labelReportIntro.setWordWrap(True)
        self.tableStatistics = QtWidgets.QTableWidget(0, 2, self.tabReport)
        self.tableStatistics.setHorizontalHeaderLabels(["Metrik", "Değer"])
        self.tableStatistics.setAlternatingRowColors(True)
        self.tableStatistics.horizontalHeader().setStretchLastSection(True)
        self.btnExportReport = QtWidgets.QPushButton(self.tabReport)
        self.btnExportReport.setMinimumHeight(32)
        self.textInterpretation = QtWidgets.QTextEdit(self.tabReport)
        self.textInterpretation.setPlaceholderText("Rapor yorumları üretimden sonra burada hazırlanır.")
        self.reportTabs = QtWidgets.QTabWidget(self.tabReport)
        self.reportTabs.addTab(self.tableStatistics, "İstatistik Tablosu")
        self.reportTabs.addTab(self.textInterpretation, "Yorum ve Tez Metni")
        layout.addWidget(self.labelReportIntro)
        layout.addWidget(self.reportTabs)
        layout.addWidget(self.btnExportReport)
        self.tabWidget.addTab(self.tabReport, "")

    def _setup_run_tab(self):
        self.tabRun = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout(self.tabRun)
        self.groupMapElements = QtWidgets.QGroupBox(self.tabRun)
        elem_layout = QtWidgets.QGridLayout(self.groupMapElements)
        self.checkNorthArrow = QtWidgets.QCheckBox("Kuzey oku", self.groupMapElements)
        self.checkScaleBar = QtWidgets.QCheckBox("Ölçek çubuğu", self.groupMapElements)
        self.checkGrid = QtWidgets.QCheckBox("Koordinat ızgarası", self.groupMapElements)
        self.checkSourceInfo = QtWidgets.QCheckBox("Kaynak bilgisi", self.groupMapElements)
        self.checkLogo = QtWidgets.QCheckBox("Logo", self.groupMapElements)
        self.checkLegal = QtWidgets.QCheckBox("Yasal uyarı", self.groupMapElements)
        for index, widget in enumerate([self.checkNorthArrow, self.checkScaleBar, self.checkGrid, self.checkSourceInfo, self.checkLogo, self.checkLegal]):
            widget.setChecked(True)
            elem_layout.addWidget(widget, index // 3, index % 3)

        self.groupRun = QtWidgets.QGroupBox(self.tabRun)
        self.groupRun.setObjectName("groupRun")
        self.checkUseCache = QtWidgets.QCheckBox(self.groupRun)
        self.checkUseCache.setObjectName("checkUseCache")
        self.checkUseCache.setChecked(True)
        self.spinCacheDays = QtWidgets.QSpinBox(self.groupRun)
        self.spinCacheDays.setObjectName("spinCacheDays")
        self.spinCacheDays.setRange(1, 3650)
        self.spinCacheDays.setValue(30)
        cache_layout = QtWidgets.QHBoxLayout()
        cache_layout.addWidget(self.checkUseCache)
        cache_layout.addStretch(1)
        cache_layout.addWidget(QtWidgets.QLabel("Saklama süresi (gün)"))
        cache_layout.addWidget(self.spinCacheDays)

        self.labelDownloadStatus = QtWidgets.QLabel(self.groupRun)
        self.downloadProgress = QtWidgets.QProgressBar(self.groupRun)
        self.btnDownloadData = QtWidgets.QPushButton(self.groupRun)
        self.btnDownloadData.setMinimumHeight(38)
        self.btnDownloadData.setStyleSheet("background:#1b7f3a;color:white;font-weight:bold;")
        self.btnStopWorker = QtWidgets.QPushButton(self.groupRun)
        self.btnStopWorker.setObjectName("btnStopWorker")
        self.btnStopWorker.setMinimumHeight(32)
        self.btnStopWorker.setEnabled(False)
        self.btnStopWorker.setStyleSheet("background:#a83232;color:white;font-weight:bold;")
        self.btnClearCache = QtWidgets.QPushButton(self.groupRun)
        self.btnClearCache.setObjectName("btnClearCache")
        self.btnClearCache.setMinimumHeight(32)
        self.labelPoweredBy = QtWidgets.QLabel(self.groupRun)
        self.labelPoweredBy.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPoweredBy.setStyleSheet("font-weight:bold;color:#174a92;padding:6px;")
        self.textLog = QtWidgets.QTextEdit(self.groupRun)
        self.textLog.setReadOnly(True)
        run_layout = QtWidgets.QVBoxLayout(self.groupRun)
        run_layout.addLayout(cache_layout)
        run_layout.addWidget(self.labelDownloadStatus)
        run_layout.addWidget(QtWidgets.QLabel("Üretim ilerlemesi:", self.groupRun))
        run_layout.addWidget(self.downloadProgress)
        button_layout = QtWidgets.QHBoxLayout()
        button_layout.addWidget(self.btnDownloadData, 2)
        button_layout.addWidget(self.btnStopWorker, 1)
        button_layout.addWidget(self.btnClearCache, 1)
        run_layout.addLayout(button_layout)
        run_layout.addWidget(self.labelPoweredBy)
        run_layout.addWidget(self.textLog, 1)

        layout.addWidget(self.groupMapElements)
        layout.addWidget(self.groupRun, 1)
        self.tabWidget.addTab(self.tabRun, "")

    def retranslateUi(self, TurkeyGeoMorphDialog):
        _translate = QtCore.QCoreApplication.translate
        TurkeyGeoMorphDialog.setWindowTitle(_translate("TurkeyGeoMorphDialog", "TurkeyGeoMorph Analyst"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWorkspace), _translate("TurkeyGeoMorphDialog", "📍 Çalışma Alanı"))
        self.labelWorkspaceHelp.setText(_translate("TurkeyGeoMorphDialog", "Çalışma alanı, analiz yapılacak idari sınırı ve tüm çıktıların kaydedileceği proje klasörünü belirler. Önce il/ilçe seçin, sınırı haritada kontrol edin, sonra anlaşılır bir proje adı girin."))
        self.labelOutputHelp.setText(_translate("TurkeyGeoMorphDialog", "Tüm indirilen DEM/akarsu verileri, üretilen rasterlar, layoutlar, raporlar ve teslim paketleri bu klasörün altında saklanır. Boşluk ve Türkçe karakter kullanılabilir; dışa aktarmada güvenli dosya adları otomatik üretilir."))
        self.labelProjectNameHelp.setText(_translate("TurkeyGeoMorphDialog", "Proje adı dışa aktarılan PDF, PNG, GeoTIFF, QGIS projesi, rapor ve ZIP paketlerinin dosya ön eki olarak kullanılır. Örnek: van_yuksek_lisans_analizi."))
        self.groupBoundary.setTitle(_translate("TurkeyGeoMorphDialog", "Sınır türü"))
        self.radioProvinceBoundary.setText(_translate("TurkeyGeoMorphDialog", "İl sınırı"))
        self.radioDistrictBoundary.setText(_translate("TurkeyGeoMorphDialog", "İlçe sınırı"))
        self.radioManualBoundary.setText(_translate("TurkeyGeoMorphDialog", "Manuel sınır"))
        self.btnShowBoundary.setText(_translate("TurkeyGeoMorphDialog", "Sınırı Haritada Göster"))
        self.btnBrowseOutput.setText(_translate("TurkeyGeoMorphDialog", "Seç"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDownload), _translate("TurkeyGeoMorphDialog", "🛰️ Veri İndirme"))
        self.groupWorkflow.setTitle(_translate("TurkeyGeoMorphDialog", "İş Akışı"))
        self.labelWorkflow.setText(_translate("TurkeyGeoMorphDialog", "1) DEM kaynağını seçin. Copernicus kimliksizdir; OpenTopography API key ister. 2) Yerel DEM kullanacaksanız dosyayı seçin. 3) Akarsu verisini açarsanız OSM su yolları sınır içinde kırpılır. 4) Harita Üretimi sekmesinde sadece ihtiyacınız olan haritaları işaretleyin. 5) En sondaki Üretim & Temizlik sekmesinden üretimi başlatın."))
        self.groupDemSource.setTitle(_translate("TurkeyGeoMorphDialog", "DEM Kaynağı Seçimi"))
        self.groupCredentials.setTitle(_translate("TurkeyGeoMorphDialog", "API ve Yerel Dosya Ayarları"))
        self.btnValidateOpenTopo.setText(_translate("TurkeyGeoMorphDialog", "API Key Doğrula"))
        self.groupOsm.setTitle(_translate("TurkeyGeoMorphDialog", "OSM Akarsu Verisi (Geofabrik)"))
        self.checkDownloadRivers.setText(_translate("TurkeyGeoMorphDialog", "Akarsu verisini indir"))
        self.checkClipRivers.setText(_translate("TurkeyGeoMorphDialog", "Yalnızca seçilen il sınırındaki akarsular"))
        self.labelDownloadStatus.setText(_translate("TurkeyGeoMorphDialog", "Hazır"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMaps), _translate("TurkeyGeoMorphDialog", "🗺️ Harita Üretimi"))
        self.labelExportIntro.setText(_translate("TurkeyGeoMorphDialog", "Varsayılan güvenli dışa aktarma PDF + QGIS Projesi üretir. PNG, SVG, GeoTIFF, vektör ve ZIP paket seçeneklerini yalnızca ihtiyaç duyduğunuzda açın."))
        self.labelFormatHelp.setText(_translate("TurkeyGeoMorphDialog", "Format açıklaması: PDF baskı ve tez eki için; QGIS Projesi tüm katman/layout düzenini tekrar açmak için; PNG hızlı görsel kontrol ve sunum için; SVG düzenlenebilir vektör çıktı için; GeoTIFF GIS analiz katmanlarını saklamak için; ZIP teslim paketi tüm çıktıları tek dosyada toplamak için kullanılır. Büyük illerde 600 DPI yerine önce 150/300 DPI deneyin."))
        self.labelExportProgress.setText(_translate("TurkeyGeoMorphDialog", "Dışa aktarma ilerlemesi:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExport), _translate("TurkeyGeoMorphDialog", "💾 Dışa Aktarma"))
        self.btnGenerateAllMaps.setText(_translate("TurkeyGeoMorphDialog", "Seçili Çıktıları Kaydet ve Teslim Paketi Oluştur"))
        self.labelReportIntro.setText(_translate("TurkeyGeoMorphDialog", "İstatistikleri CSV/HTML/TXT olarak kaydedin. Rapor; yükselti aralığı, ortalama yükselti, hipsometrik integral ve üretilen harita gruplarını tez diliyle yorumlamaya yardımcı olur."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReport), _translate("TurkeyGeoMorphDialog", "📊 İstatistik & Rapor"))
        self.btnExportReport.setText(_translate("TurkeyGeoMorphDialog", "Raporu Dışa Aktar"))
        self.groupMapElements.setTitle(_translate("TurkeyGeoMorphDialog", "Layout Öğeleri"))
        self.groupRun.setTitle(_translate("TurkeyGeoMorphDialog", "Üretim ve Temizlik"))
        self.checkUseCache.setText(_translate("TurkeyGeoMorphDialog", "Önbelleği kullan"))
        self.btnDownloadData.setText(_translate("TurkeyGeoMorphDialog", "Seçili Haritaları Üret"))
        self.btnStopWorker.setText(_translate("TurkeyGeoMorphDialog", "İşlemi Durdur"))
        self.btnClearCache.setText(_translate("TurkeyGeoMorphDialog", "Önbelleği Temizle"))
        self.labelPoweredBy.setText(_translate("TurkeyGeoMorphDialog", "Powered By AGLSOFT - Ali Ganigülü™"))
        self.labelDownloadStatus.setText(_translate("TurkeyGeoMorphDialog", "Hazır"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRun), _translate("TurkeyGeoMorphDialog", "⚙️ Üretim & Temizlik"))
        self._apply_help_texts()

    def _apply_help_texts(self):
        self.cmbProvince.setToolTip("Analiz yapılacak ili seçin. İl değişince ilçe listesi otomatik güncellenir.")
        self.cmbDistrict.setToolTip("İlçe sınırı ile çalışacaksanız buradan ilçe seçin.")
        self.lineOutputFolder.setToolTip("Tüm çıktıların yazılacağı ana klasör.")
        self.lineProjectName.setToolTip("Dışa aktarılan dosyaların adlandırmasında kullanılacak proje ön eki.")
        self.lineOpenTopoKey.setToolTip("OpenTopography 30m/90m DEM indirmek için ücretsiz API anahtarı.")
        self.fileLocalDem.setToolTip("Kendi DEM dosyanızı kullanmak için GeoTIFF/HGT/IMG/VRT vb. raster seçin.")
        self.checkDownloadRivers.setToolTip("OSM akarsu ağını indirir ve seçilen sınıra göre kırpar.")
        self.cmbRiverFilter.setToolTip("Akarsu tiplerini seçin: river/stream/canal/drain gibi OSM waterway sınıfları.")
        self.checkUseCache.setToolTip("Aynı il/ilçe ve DEM kaynağı tekrar seçilirse veriyi yeniden indirmeden önbellekten kullanır.")
        self.spinCacheDays.setToolTip("Önbellekteki DEM ve akarsu verilerinin kaç gün saklanacağını belirler.")
        self.cmbPngDpi.setToolTip("150 DPI hızlı kontrol, 300 DPI tez baskısı, 600 DPI büyük ve yavaş yüksek çözünürlük çıktısıdır.")
        self.lineExportPrefix.setToolTip("Boş bırakılırsa Çalışma Alanı sekmesindeki proje adı kullanılır.")
        self.treeExportFiles.setToolTip("Üretilecek veya üretilmiş dosyaların önizleme ve durum listesidir.")
        self.tableStatistics.setToolTip("DEM ve morfometrik analizlerden gelen sayısal sonuçlar.")
        self.textInterpretation.setToolTip("Otomatik üretilen yorum metni; tez metnine uyarlanabilir.")
